'''
THIS PROGRAM SHOWS HOW TO CRAFT AND MANIPULATE PACKETS
'''

# IMPORT SCAPY MODULE
from scapy.all import *

# PACKETS ARE BUILT IN LAYERS. A TCP PACKET CONSISTS OF
# ETHER, IP, TCP AND THEN ANY EXTRA DATA. BELOW YOU CAN SEE
# US DEFYNING THE PACKET LAYERS. FOR NOW I AM NOT GOING TO WORRY
# ABOUT PASSING USELESS DATA (E.G. DATA ABOUT OURSELF) INT0 OUR PACKET.
# ANY CRITICAL DATA SHOULD BE COVERED BY SCAPY

pkt = Ether()/IP(dst='127.0.0.1', ttl=225)/TCP(sport=80, dport=80)/Raw(load='this is raw data')
send(pkt, verbose=0)
# THIS WOULD SEND 1 TCP PACKET TO 127.0.0.1:80 FROM YOURIP:80 WITH A TTL OF 225 AND SOME RAW DATA AT THE END

# SCAPY ALLOWS US TO DO BAD THINGS TOO.

pkt = Ether()/IP(src='192.168.1.1', dst='127.0.0.1', ttl=64)/TCP(sport=80, dport=80)/Raw(load='Spoofed packet :)')
# THIS IS AN EXAMPLE OF SPOOFINF OUR PACKETS ADDRESS. THIS PARTICULAR EXAMPLE
# WOULD DO THE SAME AS ABOVE, BUT FROM '192.168.1.2' (BUT REALLY FROM US)
# THIS ALLOWS US TO DO CERTAIN THINGS SUCH AS BYPASS WEAK FIREWALLS, SPOOF
# DATA ETC. THE ONLY PROBLEM IS THAT SINCE WE HAVE CHANGED THE SOURCE ADDRESS,
# YOU WILL NOT GET ANY DATA BACK. SO IT'S LITERALLY USELESS FOR ANY TYPE OF
# ATTACK WHERE YOU NEED A RESPONSE OF ANY KIND.

##############

# PICTURE THIS SITUATION. SOMEONE HAS A SMART HOME.
# THEIR 'SMART' LOCK OPENS AND CLOSES WHEN THEIR PHONE SENDS THEM THE 'ok'
# SIGNAL. QUICK RECON WOULD TELL YOU THEIR PHONE OPERATES AT 192.168.1.14:40
# AND THE LOCK IS AT 192.168.1.99:30
# SO HOW CAN WE FORGE SUCH DATA? WELL:
pkt = Ether()/IP(src='192.168.1.14', dst='192.168.1.99')/TCP(sport=40,dport=30)/Raw(load='unlock me or whatever')
send(pkt, verbose=0)

# THIS WOULD (IN THIS SITUATION) UNLOCK OUR TARGETS DOOR.

#############

# CRAFTING PACKETS OF DIFFERENT PROTOCOLS IS EQUALLY AS EASY:
pkt=Ether()/IP(dport='127.0.0.1')/UDP(sport=123,dport=80)

